version: "3.7"

services:
  nxa-postgres:
    image: postgres:15.3-alpine
    restart: always
    container_name: nxa-postgres
    ports:
      - 5432:5432
    env_file:
      - ./postgres.env
    volumes:
      - nxa-postgres-data:/var/lib/postgresql/data
    networks:
      - nxa-network

  nxa-clickhouse-db:
    container_name: nxa-olap-clickhouse-server
    restart: always
    image: clickhouse/clickhouse-server:23.3.8.21-alpine
    healthcheck:
      test: apt update -y && apt install curl -y && echo 'SELECT 1' | curl 'http://localhost:8123/' --data-binary @-
      interval: 5s
      timeout: 5s
      retries: 10
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    env_file:
      - ./clickhouse.env
    ports:
      - 9000:9000
      - 8123:8123
    volumes:
      - nxa-clickhouse-data:/var/lib/clickhouse
      - nxa-clickhouse-logs:/var/log/clickhouse-server
    networks:
      - nxa-network

  numexa-auth:
    container_name: numexa-auth
    restart: always
    image: numexa-auth:dev
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    env_file:
      - ./numexa.env
      - ./clickhouse.env
    ports:
      - 8080:8080
    depends_on:
      - nxa-postgres
    networks:
      - nxa-network

  nxa-monger:
    container_name: nxa-monger
    restart: always
    image: numexa-monger:dev
    build:
      context: .
      dockerfile: ./monger-proxy/Dockerfile
    env_file:
      - ./numexa.env
      - ./clickhouse.env
    ports:
      - 8081:8081
    depends_on:
      - nxa-postgres
      - nxa-clickhouse-db
    networks:
      - nxa-network

  nxa-vibe:
    container_name: nxa-vibe
    restart: always
    image: numexa-vibe:dev
    build:
      context: .
      dockerfile: ./vibe/Dockerfile
    env_file:
      - ./numexa.env
      - ./clickhouse.env
    ports:
      - 8082:8082
    depends_on:
      - nxa-clickhouse-db
    networks:
      - nxa-network

  nxa-ui:
    container_name: nxa-ui
    restart: always
    image: numexa-ui:dev
    env_file:
      - ./numexa.env
      - ./dev.env
    ports:
      - 3000:3000
    depends_on:
      - nxa-monger
      - nxa-vibe
    networks:
      - nxa-network

  numexa-cache:
    container_name: nxa-cache
    restart: always
    image: zilliz/gptcache:latest
    ports:
      - 8000:8000
    networks:
      - nxa-network

networks:
  nxa-network:
    driver: bridge

volumes:
  nxa-postgres-data:
    driver: local
  nxa-clickhouse-data:
    driver: local
  nxa-clickhouse-logs:
    driver: local
