// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package postgresql_db

import (
	"database/sql"
	"time"
)

type NxaApiKey struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	ApiKey    string    `json:"api_key"`
	UserID    int32     `json:"user_id"`
	ProjectID int32     `json:"project_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Organization struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Project struct {
	ID             int32          `json:"id"`
	OrganizationID int32          `json:"organization_id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
}

type ProjectUser struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
	UserID    int32 `json:"user_id"`
	RoleID    int32 `json:"role_id"`
}

type Role struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID             int32     `json:"id"`
	OrganizationID int32     `json:"organization_id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	Password       string    `json:"password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
